apiVersion: apps/v1
kind: Deployment
metadata:
    name: ftps
spec:
    selector:
        matchLabels:
            app: ftps
    template:
        metadata:
            labels:
                app: ftps
        spec:
            containers:
                - name: ftps
                  image: ftps:0
                  ports:
                      - containerPort: 21
                        protocol: TCP
                      - containerPort: 20000
                        protocol: TCP
                      - containerPort: 20001
                        protocol: TCP
                  livenessProbe:
                      initialDelaySeconds: 30
                      periodSeconds: 10
                      timeoutSeconds: 5
                      tcpSocket:
                          port: 21

---
apiVersion: v1
kind: Service
metadata:
    name: ftps
    annotations:
        metallb.universe.tf/allow-shared-ip: "share ip"
spec:
    type: LoadBalancer
    loadBalancerIP: 192.168.99.100
    ports:
        - port: 21
          name: ftp-data
        - port: 20000
          name: pasv1
        - port: 20001
          name: pasv2
    selector:
        app: ftps
