apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress
spec:
    replicas: 1
    selector:
        matchLabels:
            app: wordpress
    template:
        metadata:
            labels:
                app: wordpress
        spec:
            containers:
                - name: wordpress
                  image: wordpress:0
                  ports:
                      - containerPort: 5050
                        protocol: TCP
                  livenessProbe:
                      initialDelaySeconds: 30
                      periodSeconds: 10
                      timeoutSeconds: 5
                      httpGet:
                          port: 5050

---
apiVersion: v1
kind: Service
metadata:
    name: wordpress
    annotations:
        metallb.universe.tf/allow-shared-ip: "share ip"
spec:
    type: LoadBalancer
    loadBalancerIP: 192.168.99.100
    ports:
        - port: 5050
          protocol: TCP
    selector:
        app: wordpress
