apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx
                  image: nginx:0
                  ports:
                      - containerPort: 80
                        protocol: TCP
                        name: http
                      - containerPort: 443
                        protocol: TCP
                        name: https
                  livenessProbe:
                      initialDelaySeconds: 30
                      periodSeconds: 10
                      timeoutSeconds: 5
                      httpGet:
                          port: 80

---
apiVersion: v1
kind: Service
metadata:
    name: nginx
    annotations:
        metallb.universe.tf/allow-shared-ip: "share ip"
spec:
    type: LoadBalancer
    loadBalancerIP: 192.168.99.100
    ports:
        - port: 80
          protocol: TCP
          name: http
        - port: 443
          protocol: TCP
          name: https
    selector:
        app: nginx
