apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        ports:
        - containerPort: 5050

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared"
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: wordpress
  ports:
  - name: wordpress
    port: 5050
    protocol: TCP
    targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress
spec:
    replicas: 1
    selector:
        matchLabels:
            labels:
                app: wordpress
    template:
        metadata:
            labels:
                app: wordpress
        spec:
            containers:
                - name: wordpress
                  image: wordpress
                  ports:
                      - containerPort: 80
                        protocol: TCP
                        name: http
                      - containerPort: 443
                        protocol: TCP
                        name: https
---
apiVersion: v1
kind: Service
metadata:
    name: wordpress
spec:
    type: LoadBalancer
    ports:
        - port: 5050
          protocol: TCP
          name: http
        - port: 5050
          protocol: TCP
          name: https
    selector:
        app: wordpress
