apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
              - name: nginx
                image: nginx:0
                ports:
                    - containerPort: 80
                      protocol: TCP
                      name: http
                    - containerPort: 443
                      protocol: TCP
                      name: https
---
apiVersion: v1
kind: Service
metadata:
    name: nginx
spec:
    type: LoadBalancer
    ports:
        - port: 80
          protocol: TCP
          name: http
        - port: 443
          protocol: TCP
          name: https
    selector:
        app: nginx

