apiVersion: apps/v1
kind: Deployment
metadata:
    name: phpmyadmin
spec:
    replicas: 1
    selector:
        matchLabels:
            app: phpmyadmin
    template:
        metadata:
            labels:
                app: phpmyadmin
        spec:
            containers:
                - name: phpmyadmin
                  image: phpmyadmin:0
                  ports:
                      - containerPort: 5000
                        protocol: TCP
                  livenessProbe:
                      initialDelaySeconds: 30
                      periodSeconds: 10
                      timeoutSeconds: 5
                      httpGet:
                          port: 5000
                  
---
apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin
    annotations:
        metallb.universe.tf/allow-shared-ip: "share ip"
spec:
    type: LoadBalancer
    loadBalancerIP: 192.168.99.100
    ports:
        - port: 5000
          protocol: TCP
    selector:
        app: phpmyadmin
